#version: '3.8'

services:
  web:
    build: .
    expose:
      - "5000"  # Internal port for Flask app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://username:password@db:5432/postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"    # Expose HTTP port
  #     - "443:443"  # Expose HTTPS port
  #   volumes:
  #     - ./cert.pem:/etc/nginx/cert.pem  # SSL certificate
  #     - ./key.pem:/etc/nginx/key.pem    # SSL key
  #     - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx config
    # depends_on:
    #   - web

volumes:
  postgres_data:
